version: '3.8'

services:
  web:
    build: .
    command: python /docker-django/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/docker-django
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db

  db:
    image: postgres:11
    environment: 
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB:  postgres
    restart: always
    ports:
      - '5432'